# Copyright 2023 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

# Run all lint checks
name: lint
on: [push, pull_request]

jobs:

  ################
  # Verible Lint #
  ################
  verible-lint:
    name: Lint Verilog sources
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chipsalliance/verible-linter-action@main
        with:
          paths: |
            ./hw
          exclude_paths: |
            ./hw/vendor
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_error: true
          reviewdog_reporter: github-check
          extra_args: "--waiver_files util/lint/waiver.verible"
          verible_version: "v0.0-3318-g8d254167"

  #####################
  # Vendor Up-to-Date #
  #####################
  bender-vendor-up-to-date:
    name: Check bender vendor up-to-date
    runs-on: ubuntu-latest
    steps:
      - name: Check bender vendor up-to-date
        uses: pulp-platform/pulp-actions/bender-vendor-up-to-date@v2.1.0

  #################
  # Check License #
  #################
  license-lint:
    name: Check License headers
    runs-on: ubuntu-latest
    steps:
      - name: Check License
        uses: pulp-platform/pulp-actions/lint-license@v2.1.0
        with:
          patches: 0001-Allow-hash-comments-in-assembly.patch
          # We cover ETH Zurich and lowRISC licenses and Apache 2.0
          # (mostly for SW) and Solderpad for the hardware.
          # yamllint disable rule:line-length
          license: |
            Copyright (\d{4}(-\d{4})?\s)?(ETH Zurich and University of Bologna|lowRISC contributors).
            (Solderpad Hardware License, Version 0.51|Licensed under the Apache License, Version 2.0), see LICENSE for details.
            SPDX-License-Identifier: (SHL-0.51|Apache-2.0)
          # yamllint enable rule:line-length
          match_regex: true
          exclude_paths: |
            hw/vendor/*
            util/solder/solder.*.tpl
            target/sim/wave/all_cores.do
            util/addrmap/addrmap.tex.tpl

  ##################
  # Lint YML Files #
  ##################
  yaml-lint:
    name: Lint YAML Sources
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3
        with:
          config_file: util/lint/.yamllint.yml

  ########################
  # Check Python Sources #
  ########################
  python-lint:
    runs-on: ubuntu-latest
    name: Lint Python Sources
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          max-line-length: "100"

  ######################
  # Clang-Format Check #
  ######################
  # Check C/C++ files for correct formatting.
  clangfmt:
    name: Lint C/C++ Sources
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/pulp-platform/occamy:main
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      # Re-use .clang-format from Snitch cluster
      - name: Get snitch_cluster dependency
        run: |
          bender update
      - name: Lint C sources
        uses: DoozyX/clang-format-lint-action@v0.16.2
        with:
          clangFormatVersion: 10

  ######################
  # Lint Editor Config #
  ######################
  # Detect trailing whitespaces, missing new lines and wrong file encodings.
  editorconfig-lint:
    name: Lint Editorconfig
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: editorconfig-checker/action-editorconfig-checker@main
      - run: editorconfig-checker
